=== consultant-1379/probe_captool/conf/classification.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!-- TBD: could we use entities and entity references (or IDs and IDREFs) to ensure most of the additional constraints described in the comments below? -->

<!ELEMENT classification (global,block+)>

<!ELEMENT global (classifier*,facet+)>

<!ELEMENT classifier EMPTY>

<!ATTLIST classifier name ID #REQUIRED>
<!-- Should be unique among all classifiers and should not conflict with any sigId within block elements neither -->
<!ATTLIST classifier sigId CDATA #REQUIRED>
<!ATTLIST classifier standalone (true|false) "false">
<!ATTLIST classifier final (true|false) "false">

<!ELEMENT facet EMPTY>
<!ATTLIST facet name ID #REQUIRED>
<!ATTLIST facet required (true|false) "false">

<!ELEMENT block (tag*,signature+,precondition?,rule*)>
<!ATTLIST block name ID #REQUIRED>

<!ELEMENT tag EMPTY>
<!-- Has to be a valid facet name declared within the global element -->
<!ATTLIST tag name CDATA #REQUIRED>
<!ATTLIST tag value CDATA #REQUIRED>

<!-- Note that tags should only be assigned to standalone signatures -->
<!ELEMENT signature (tag*,(port|ip-range|dpi|sequence-number|p2p-host|http|http-header|http-request-body|http-response-body|ip-protocol))>
<!-- Signature IDs have to be unique within one block -->
<!ATTLIST signature id CDATA #REQUIRED>
<!ATTLIST signature standalone (true|false) "false">
<!-- final="true" implies standalone="true" -->
<!ATTLIST signature final (true|false) "false">

<!ELEMENT precondition (exclude*,allow*,constraint*)>

<!ELEMENT rule (tag*,include+,exclude*,allow*,constraint*)>
<!ATTLIST rule final (true|false) "false">

<!ELEMENT include EMPTY>
<!-- Has to be a valid sigId within the enclosing block or within the block referenced by the block attribute -->
<!ATTLIST include sigId CDATA #REQUIRED>
<!-- If present, then has to be a valid block name within the document -->
<!ATTLIST include block CDATA #IMPLIED>

<!ELEMENT exclude EMPTY>
<!-- Has to be a valid block name within the document or "all" -->
<!ATTLIST exclude block CDATA #REQUIRED>
<!-- If present, then has to be a valid facet name declared within the global element -->
<!ATTLIST exclude facet CDATA #IMPLIED>

<!ELEMENT allow EMPTY>
<!-- Has to be a valid block name within the document or "all" -->
<!ATTLIST allow block CDATA #REQUIRED>

<!ELEMENT constraint EMPTY>
<!-- Has to be a valid constraint name defined in ClassificationConstraints.h -->
<!ATTLIST constraint name CDATA #REQUIRED>

<!ELEMENT port EMPTY>
<!ATTLIST port value CDATA #REQUIRED>
<!ATTLIST port type (tcp|udp|any) "any">

<!ELEMENT ip-range (ip+)>
<!ELEMENT ip EMPTY>
<!ATTLIST ip address CDATA #REQUIRED>
<!ATTLIST ip netmask CDATA #IMPLIED>

<!ELEMENT dpi EMPTY>
<!ATTLIST dpi regexp CDATA #REQUIRED>
<!ATTLIST dpi type (tcp|udp|any) "any">

<!ELEMENT http EMPTY>

<!ELEMENT sequence-number EMPTY>
<!ATTLIST sequence-number position CDATA #REQUIRED>
<!ATTLIST sequence-number size (2|4) #REQUIRED> <!-- Currently, 2 and 4 byte long sequence numbers are supported -->
<!ATTLIST sequence-number count CDATA #REQUIRED>
<!ATTLIST sequence-number host-byte-order (true|false) "false"> <!-- Network byte order is assumed by default -->

<!ELEMENT p2p-host EMPTY>

<!ELEMENT http-header EMPTY>
<!ATTLIST http-header name CDATA #REQUIRED>
<!ATTLIST http-header regexp CDATA #REQUIRED>
<!ATTLIST http-header capture (true|false) "false">
<!-- If the capture attribute is set to true, than pattern-name should also be defined -->
<!ATTLIST http-header pattern-name CDATA #IMPLIED>

<!ELEMENT http-request-body EMPTY>
<!ATTLIST http-request-body regexp CDATA #REQUIRED>

<!ELEMENT http-response-body EMPTY>
<!ATTLIST http-response-body regexp CDATA #REQUIRED>

<!ELEMENT ip-protocol EMPTY>
<!ATTLIST ip-protocol value CDATA #REQUIRED> <!-- Should be between 0-255 and should be unique (cannot use ID to ensure this latter by DTD since a DTD ID must start with an alphabetic character) -->

=== consultant-1379/probe_captool/compiled_code/conf/classification.xml
<?xml version="1.0"?>
<!DOCTYPE classification SYSTEM "classification.dtd">

<classification>

    <!--
        Classifiers can provide hints for any application classes,
        therefore, they are listed under the "global" element.
        These hints are identified by the sigId attribute of the classifier
        which can also be used to refer to hints in rule and precondition elements.
    -->
    <global>
        <!--
            Server port search hints can used standalone to tag aplication classes
            (it relies solely on finally classified flows), however the final tagging
            of a flow based on server-port search should be avoided
        -->
        <classifier name="server-port-search" sigId="1000" standalone="true" />

        <!-- Individual NBC hints cannot be used standalone to tag application classes -->
        <!-- <classifier name="NBC" sigId="2000" /> -->

        <!-- Declaration of facets to be used to tag flows (only facets declared here can be used to define tags for blocks) -->
        <!-- A flow can be set final when it has final tags for all required facets -->
        <facet name="protocol" required="true" />
        <facet name="functionality" required="true" />
        <facet name="encapsulation" />
        <facet name="encryption" />
        <facet name="service-provider" />
        <facet name="client-application" />

    </global>

    <!-- Real Time Messaging Protocol (RTMP) from Adobe System -->
    <block name="RTMP">
        <tag name="protocol" value="RTMP" />
        <tag name="functionality" value="media-playback" />

        <signature id="1">
            <!-- Only for information purposes, not used for classification -->
            <port value="1935" type="tcp" />
        </signature>
        <signature id="2" final="true">
            <!-- Adobe Flash Media Server? -->
            <dpi regexp="fmsVer...FMS" type="tcp" />
        </signature>
        <signature id="3">
            <!-- RTMP tunneled in HTTP -->
            <http-header name="content-type" regexp="^application/x-fcs" />
        </signature>
        <signature id="4">
            <!-- RTMP tunneled in HTTP -->
            <http-header name="url" regexp="^/(open|send|idle|close)/" />
        </signature>
        <signature id="5">
            <!-- Less frequent pattern... -->
            <dpi regexp="createStream" type="tcp" />
        </signature>
        <rule final="true">
            <tag name="encapsulation" value="HTTP" />
            <include sigId="3" />
            <include sigId="4" />
        </rule>
        <rule final="true">
            <include sigId="1" />
            <include sigId="5" />
        </rule>
    </block>

    <block name="RTSP">
        <tag name="protocol" value="RTSP" />
        <tag name="functionality" value="media-playback" />

        <signature id="1">
            <!-- Only for information purposes, not used for classification -->
            <port value="554" type="tcp" />
        </signature>
        <signature id="2" final="true">
            <dpi regexp="^RTSP/\d\.\d" type="tcp" />
        </signature>
        <signature id="3" final="true">
            <dpi regexp="^DESCRIBE rtsp\://" type="tcp" />
        </signature>
    </block>

    <block name="RTP">
        <tag name="protocol" value="RTP" />

        <signature id="1">
            <!-- Only for information purposes, not used for classification -->
            <port value="5004" type="udp" />
        </signature>
        <signature id="2" standalone="true">
            <!-- 16 bit RTP sequence number at position 2 -->
            <sequence-number position="2" size="2" count="8" />
        </signature>
        <precondition>
            <constraint name="rtp-header" />
        </precondition>
        <rule>
            <tag name="functionality" value="media-playback" />
            <include sigId="2" />
            <constraint name="unidirectional-flow" />
        </rule>
        <rule>
            <tag name="functionality" value="VoIP" />
            <include sigId="2" />
            <constraint name="symmetric-flow" />
        </rule>
    </block>

    <!-- Other misc realtime streaming -->
    <block name="streaming-realtime-http">
        <tag name="functionality" value="media-playback" />

        <!-- Streaming protocol used by SHOUTcast servers (developed by Nullsoft) -->
        <signature id="1" standalone="true">
            <dpi regexp="^ICY " type="tcp" />
        </signature>
        <signature id="2" standalone="true">
            <tag name="client-application" value="Winamp" />
            <http-header name="user-agent" regexp="^WinampMPEG"/>
        </signature>
        <signature id="4">
            <!-- Quative IPTV Service Delivery Platform (QSP) -->
            <http-header name="user-agent" regexp="^QSP " />
        </signature>
        <signature id="5">
            <!-- Quative IPTV Service Delivery Platform (QSP) -->
            <http-header name="content-type" regexp="^application/qss" />
        </signature>
        <rule final="true">
            <include sigId="4" />
            <include sigId="5" />
        </rule>
    </block>

    <block name="online-media">
        <tag name="functionality" value="media-playback" />

        <signature id="3">
            <!-- Microsoft Media Player (Note that it can also act as a simple browser) -->
            <http-header name="user-agent" regexp="^(NS|WM)Player/" />
        </signature>
        <signature id="4" standalone="true">
            <!-- MP4 container, see http://www.ftyps.com/ (can be both audio and video) -->
            <!-- Note that theoretically, this container could also be used for image files (but I have never seen such example) -->
            <http-response-body regexp="^....ftyp" />
        </signature>

        <precondition>
            <!-- Use the more specific audio and video tags instead of the generic media term whenever possible -->
            <exclude block="online-video" />
            <exclude block="online-audio" />
        </precondition>
    </block>

    <block name="smartphone-media-player">
        <signature id="1" standalone="true">
            <!-- Android Media Player -->
            <tag name="client-application" value="Android-Media-Player" />
            <http-header name="user-agent" regexp="^(CORE|PVCore|stagefright|HTC Streaming)" />
        </signature>
        <signature id="2" standalone="true">
            <!-- iPhone Media Player -->
            <tag name="client-application" value="iPhone-Media-Player" />
            <http-header name="user-agent" regexp="CoreMedia" />
        </signature>
        <signature id="3" standalone="true">
            <tag name="client-application" value="LetvIphoneClient" />
            <http-header name="user-agent" regexp="^LetvIphoneClient" />
        </signature>

        <!-- Most of these media players can also act as web-browsers -->
        <rule>
            <tag name="functionality" value="web-browsing" />
            <include sigId="1" />
            <exclude block="online-video" />
            <exclude block="online-audio" />
            <exclude block="online-media" />
            <exclude block="contenttype" />
        </rule>
        <rule>
            <tag name="functionality" value="web-browsing" />
            <include sigId="2" />
            <exclude block="online-video" />
            <exclude block="online-audio" />
            <exclude block="online-media" />
            <exclude block="contenttype" />
        </rule>
    </block>

    <block name="online-video">
        <tag name="functionality" value="video-playback" />

        <signature id="1" final="true">
            <http-header name="content-type" regexp="^video/" />
        </signature>
        <!-- FLV container -->
        <signature id="2" final="true">
            <http-response-body regexp="^FLV" />
        </signature>
        <signature id="3" final="true">
            <!-- Will only match if HTTP traffic does not bypass the DPI module -->
            <dpi regexp="^FLV" type="tcp" />
        </signature>
        <signature id="4">
            <!-- some qbrick videos -->
            <http-header name="url" regexp="segment[0-9]+\.ts$" />
        </signature>
    </block>

    <block name="online-audio">
        <tag name="functionality" value="audio-playback" />

        <signature id="1">
            <!-- Can also be very short audio content, e.g. playback of one single word for dictionnary pages or other sound effects on web pages -->
            <!-- This generic content-type pattern might also include playlists, etc. -->
            <http-header name="content-type" regexp="^audio/" />
        </signature>
        <signature id="2">
            <!-- can also be file download -->
            <http-header name="url" regexp="\.mp3$" />
        </signature>
        <signature id="3" standalone="true">
            <!-- Covers several iPhone web-radio apps  -->
            <http-header name="user-agent" regexp="[Rr]adio" />
        </signature>
        <signature id="4" standalone="true">
            <!-- Icecast streaming audio -->
            <!-- Many iPhone web-radio apps are powered by this server -->
            <http-header name="server" regexp="^Icecast" />
        </signature>
        <signature id="5" standalone="true">
            <!-- Pandora radio -->
            <http-header name="host" regexp="^audio-.*\.pandora\.com$" />
        </signature>
        <signature id="6" standalone="true">
            <!-- Slacker radio -->
            <http-header name="host" regexp="^(signal|sidesync).*\.slacker\.com$" />
        </signature>
        <rule>
            <!-- Audio content type + MP4 media container -->
            <include sigId="1" />
            <include block="online-media" sigId="4" />
        </rule>
        <rule>
            <!-- Audio content type + audio file extension -->
            <include sigId="1" />
